name: Cypress Tests

on:
  push:
    branches: [ feature/* ]

jobs:
  check-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18.14.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1

      - name: Install dependencies
        run: |
          npm ci

      - name: Check linting
        run: npm run lint
        continue-on-error: false

  install:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist
  
  components-test:
    runs-on: ubuntu-22.04
    container: cypress/browsers:18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: 'Components test'
        uses: cypress-io/github-action@v5
        with:
          component: true
          browser: chrome
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
